### ISSUE TITLE
name in deeparg database is not consistant

### ISSUE THREAD

**Issue by cocodyq** [AdeBC/quick_amr_db_harmonisation#1]
The format of Original ID : YP_691420|[u'multidrug']|MdtN|unknown in deeparg_ARO_mapping.tsv
is not consistant with gene_name: YP_691420|FEATURES|mdtN|multidrug|mdtN in https://github.com/BigDataBiology/arg-compare/blob/master/computed/deeparg.tsv.xz
Don't know why the original ID all have [u''].And can you change it to the same format of gene_name?

**Comment by AdeBC** [comment]
Thank you for raising this issue.

I've fixed this by using sequence names from their [new database](https://bitbucket.org/gusphdproj/deeparg-largerepo/src/master/database/v2/features.fasta).

Please use the latest mapping table.
